name: router_example
description: An example project for the flutter router.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluro:
    path: ../
  shared_preferences: 2.0.5
flutter:
  uses-material-design: true

dev_dependencies:
  integration_test:
  test: any