name: router_example
description: An example project for the flutter router.

dependencies:
  flutter:
    sdk: flutter
  fluro:
    path: ../
  shared_preferences: ^0.5.10
flutter:
  uses-material-design: true