name: fluro
description: >
  Fluro is a Flutter routing library that adds flexible routing options like wildcards, named
  parameters and clear route definitions.
version: 2.1.0
homepage: https://github.com/theyakka/fluro

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_platform: ^0.1.3
  universal_html: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.7

flutter:
  uses-material-design: false
